# For an explanation of these configuration settings, please visit
# http://dev.bukkit.org/server-mods/hidestream/pages/config-explanation/ 

Enabled: true
UseVault: false
CheckForUpdates: true
DebugMode: false
NoCommandPermissionMsg: '&cNo permission.'
PerPlayerToggle:
  Enable: false
  StreamEnabledByDefault: true
Join:
  HideJoinStream: true
  NeedsToBeOnline: 0
  Permissions:
    UsePermissions: false
    HideOnlyIfHasPermission: false
    HideOnlyIfWithoutPermission: false
  OPSupport:
    Enabled: false
    OnlyHideIfNotOP: false
    OnlyHideIfOP: false
Quit:
  HideQuitStream: true
  NeedsToBeOnline: 0
  Permissions:
    UsePermissions: false
    HideOnlyIfHasPermission: false
    HideOnlyIfWithoutPermission: false
  OPSupport:
    Enabled: false
    OnlyHideIfNotOP: false
    OnlyHideIfOP: false
Kick:
  HideKickStream: true
  NeedsToBeOnline: 0
  Permissions:
    UsePermissions: false
    HideOnlyIfHasPermission: false
    HideOnlyIfWithoutPermission: false
  OPSupport:
    Enabled: false
    OnlyHideIfNotOP: false
    OnlyHideIfOP: false
Death:
  HideDeathStream: false
  NeedsToBeOnline: 0
  Permissions:
    UsePermissions: false
    HideOnlyIfHasPermission: false
    HideOnlyIfWithoutPermission: false
  OPSupport:
    Enabled: false
    OnlyHideIfNotOP: false
    OnlyHideIfOP: false
