AntiJoinBot:
  MySQL:
    Offline: true
    Host: localhost
    Port: 3306
    Database: ajb_intelligent_blacklist
    User: <username>
    Password: <password>
  Blacklists:
    http://www,shroomery,org/ythan/proxycheck,php?ip=: Y
    http://yasb,intuxication,org/api/check,xml?ip=: <spam>true</spam>
    http://www,stopforumspam,com/api?ip=: 'yes'
  ServerListPing:
    Enabled: false
    Message: Don't use a Proxy :P
  Force:
    Enabled: false
    Message: Proxy Check... pls. reJoin!
  Kick:
    Message: Proxy is Detected. (maybe an error please reconnect your Router)
  Warmup:
    Enabled: true
    Seconds: 60
  Debug:
    Enabled: false
