# Jobs configuration.
# 
# Stores information about each job.
# 
# For example configurations, visit http://dev.bukkit.org/server-mods/jobs/.

Jobs:
  Woodcutter:
    fullname: LENHADOR
    shortname: L
    ChatColour: GREEN
    chat-display: none
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Break:
      LOG:
        income: 5.0
        experience: 5.0
    Place:
      SAPLING:
        income: 1.1
        experience: 1.0
      WOOD:
        income: 0.5
        experience: 2.0
    Kill:
      Player:
        income: 5.0
        experience: 7.5
    custom-kill:
      Lenhador:
        income: 7.0
        experience: 10.0
    permissions:
      aaaaaatest.node:
        value: true
        level: 0
      aaaaaatest.node2:
        value: true
        level: 10
  Miner:
    fullname: MINERADOR
    shortname: M
    ChatColour: DARK_GRAY
    chat-display: none
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Break:
      STONE:
        income: 5.0
        experience: 2.0
      COAL_ORE:
        income: 0.1
        experience: 3.0
      REDSTONE_ORE:
        income: 2.0
        experience: 3.0
      IRON_ORE:
        income: 0.5
        experience: 4.0
      GOLD_ORE:
        income: 5.0
        experience: 5.0
      LAPIS_ORE:
        income: 0.5
        experience: 5.0
      DIAMOND_ORE:
        income: 7.0
        experience: 6.0
      OBSIDIAN:
        income: 7.5
        experience: 7.5
      MOSSY_COBBLESTONE:
        income: 3.0
        experience: 6.0
    Place:
      RAILS:
        income: 0.5
        experience: 2.0
      IRON_ORE:
        income: -5.0
        experience: -5.0
      GOLD_ORE:
        income: -6.0
        experience: -6.0
    Kill:
      Player:
        income: 7.5
        experience: 7.5
    custom-kill:
      Minerador:
        income: 10.0
        experience: 10.0
  Builder:
    fullname: CONSTRUTOR
    shortname: C
    ChatColour: WHITE
    chat-display: none
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Place:
      COBBLESTONE:
        income: 3.0
        experience: 1.0
      WOOD:
        income: 2.0
        experience: 1.5
      FENCE:
        income: 0.5
        experience: 1.5
      WOOL:
        income: 0.5
        experience: 1.5
      STONE:
        income: 2.0
        experience: 2.25
      GLOWSTONE:
        income: 0.5
        experience: 3.0
      SANDSTONE:
        income: 0.5
        experience: 2.0
      GLASS:
        income: 2.5
        experience: 3.0
      BRICK:
        income: 0.5
        experience: 4.0
      LAPIS_BLOCK:
        income: 0.5
        experience: 5.0
      DOUBLE_STEP:
        income: 0.5
        experience: 2.0
      STEP:
        income: 0.5
        experience: 2.0
      BOOKSHELF:
        income: 0.5
        experience: 3.0
      WOOD_STAIRS:
        income: 0.5
        experience: 2.0
      COBBLESTONE_STAIRS:
        income: 0.5
        experience: 2.0
      MOSSY_COBBLESTONE:
        income: 1.0
        experience: 5.0
      DIAMOND_BLOCK:
        income: 2.0
        experience: 5.0
      GOLD_BLOCK:
        income: 1.0
        experience: 5.0
    Kill:
      Player:
        income: 7.5
        experience: 7.5
    custom-kill:
      Construtor:
        income: 10.0
        experience: 10.0
  Digger:
    fullname: ESCAVADOR
    shortname: E
    ChatColour: GOLD
    chat-display: none
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Break:
      DIRT:
        income: 2.5
        experience: 2.0
      GRASS:
        income: 0.5
        experience: 2.0
      GRAVEL:
        income: 2.5
        experience: 2.0
      SAND:
        income: 1.5
        experience: 2.0
      CLAY:
        income: 0.5
        experience: 2.0
    Kill:
      Player:
        income: 5.0
        experience: 7.5
    custom-kill:
      Escavador:
        income: 7.0
        experience: 10.0
  Farmer:
    fullname: FAZENDEIRO
    shortname: Ag
    ChatColour: BLUE
    chat-display: none
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Break:
      CROPS-7:
        income: 2.5
        experience: 4.0
    Place:
      CROPS-0:
        income: 2.5
        experience: 3.0
    Kill:
      Player:
        income: 5.0
        experience: 7.5
    custom-kill:
      Agricultor:
        income: 7.0
        experience: 10.0
  Hunter:
    fullname: CACADOR
    shortname: C
    ChatColour: RED
    chat-display: none
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Kill:
      Chicken:
        income: 1.5
        experience: 2.5
      Cow:
        income: 2.5
        experience: 2.5
      Pig:
        income: 1.5
        experience: 2.5
      Sheep:
        income: 1.5
        experience: 2.5
      Wolf:
        income: 2.5
        experience: 5.0
      Creeper:
        income: 3.5
        experience: 10.0
      Skeleton:
        income: 1.5
        experience: 10.0
      Spider:
        income: 1.0
        experience: 10.0
      Zombie:
        income: 1.0
        experience: 10.0
      Player:
        income: 2.0
        experience: 7.5
    custom-kill:
      Lenhador:
        income: 5.0
        experience: 10.0
      Minerador:
        income: 5.0
        experience: 10.0
      Escavador:
        income: 5.0
        experience: 10.0
      Agricultor:
        income: 1.0
        experience: 10.0
      Construtor:
        income: 1.0
        experience: 10.0
      Cacador:
        income: 10.0
        experience: 20.0
  Fisherman:
    fullname: PESCADOR
    shortname: Pe
    ChatColour: AQUA
    chat-display: none
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Fish:
      RAW_FISH:
        income: 5.0
        experience: 4.0
    Kill:
      Player:
        income: 5.0
        experience: 7.5
    custom-kill:
      PEscador:
        income: 7.0
        experience: 10.0
  Weaponsmith:
    fullname: FERREIRO
    shortname: W
    ChatColour: GRAY
    chat-display: none
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Craft:
      WOOD_SWORD:
        income: 2.0
        experience: 2.0
      IRON_SWORD:
        income: 3.0
        experience: 3.0
      GOLD_SWORD:
        income: 3.0
        experience: 3.0
      DIAMOND_SWORD:
        income: 4.0
        experience: 4.0
    Smelt:
      IRON_INGOT:
        income: 2.0
        experience: 2.0
      GOLD_INGOT:
        income: 2.0
        experience: 2.0
  Brewer:
    fullname: MAGO
    shortname: Ce
    ChatColour: DARK_PURPLE
    chat-display: none
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Brew:
      NETHER_STALK:
        income: 1.0
        experience: 1.0
      REDSTONE_DUST:
        income: 2.0
        experience: 2.0
      GLOWSTONE_DUST:
        income: 2.0
        experience: 2.0
      SPIDER_EYE:
        income: 2.0
        experience: 2.0
      FERMENTED_SPIDER_EYE:
        income: 2.0
        experience: 2.0
      BLAZE_POWDER:
        income: 2.0
        experience: 2.0
      SUGAR:
        income: 2.0
        experience: 2.0
      SPECKLED_MELON:
        income: 4.0
        experience: 4.0
      MAGMA_CREAM:
        income: 4.0
        experience: 4.0
      GHAST_TEAR:
        income: 4.0
        experience: 4.0
  Enchanter:
    fullname: ENCANTADOR
    shortname: E
    ChatColour: DARK_BLUE
    chat-display: none
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Enchant:
      WOOD_SWORD:
        income: 4.0
        experience: 4.0
      IRON_SWORD:
        income: 6.0
        experience: 6.0
      GOLD_SWORD:
        income: 8.0
        experience: 8.0
      DIAMOND_SWORD:
        income: 10.0
        experience: 10.0
  None:
    fullname: None
    shortname: N
    ChatColour: WHITE
    chat-display: none
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Kill:
      Player:
        income: 7.5
