# This is the AntiRelog configuration file.
# Editing this file with Notepad++ is strongly recommended.
# Save the file and reload the server after you are done editing for changes to take place.
# Here are the explanations for each option:
# MOTD: This field contains the message that players will see when they join the server. Set enabled to true or false to toggle on or off.
# MOTD Message: Displays the message players will see when they join the server.
# 
# Mob Logger: Set this to true enable AntiRelog for hostile mobs. Players who log off during combat will face the same consequences as if they logged against another player.
# Passive Mob Logger: Set this to true to enable Mob Logger for passive mobs. Must have Mob Logger enabled to use this.
# 
# Tag Message: This is the message sent when players enter combat.
# UnTag Message: This is the message sent when players are not in combat anymore.
# 
# Ban Duration: This defines the amount of time in MINUTES that a player will be banned if he/she logs off while in combat. Set to 0 to disable this feature.
# Ban Message: Players who have been temporarily banned from PvP logging will see this message if they try to connect.
# Ban Broadcast: Set this to true to alert all players on the server when someone combat logs.
# Ban Broadcast Message: This message will be displayed to everyone on the server when a player logs off while in combat.
# 
# Unban Message Enabled: Set this to true to send a message to players when they log on after being unbanned.
# Unban Message: This is the message that will be sent to players when they log on after being unbanned.
# Unban Runnbale Commands: Now, you can run multiple commands when a previously banned player logs on. You can use this along with economy plugins to penalize combat loggers. Set first line of list to 'null' to disable this.
# 
# NPC: Setting this to true spawns an NPC in place of the combat logger. The NPC will fight back and drop the items if killed. If the NPC kills the attacker, it will despawn.
# NPC Despawn Delay: Defines the number of seconds before the NPC is despawned.
# NPC Default Aggressive: Set this to true to make all spawned NPCs defend themselves and attack the enemy. If set to false, individual permission nodes can be assigned giving the 'antirelog.aggressivenpc' node.
# 
# Drops: If these are set to true, the player will drop that equipment/item upon combat logging. If NPCs are enabled, the NPC will drop those items upon being killed.
# 
# Disallow All: Set this to true to disallow all commands while in PVP. (Overrides command list).
# Freeze Duration: This defines the amount of time in SECONDS that players must wait before using commands if they are hit. Set to 0 if you want to disable this feature.
# Freeze Message: This sets the message shown if players try to use a command during PVP.
# DisallowedCMDs: This is a list of the disallowed commands. Add to the list using the same format as shown. Set first line to 'null' to allow all commands.
MOTD:
  Enabled: false
  Message: <yellow>Bem-vindo ao craftbosspvp.
Mobs:
  Logger-Enabled: false
  Passive-Logger-Enabled: false
PvP:
  Tag-Message:
    Enabled: true
    Tag: <red>Você foi atacado e agora está em combate, se sair será penalizado e perdera todos os itens.
    Un-Tag: <green>Você não está mais em combate.
  Ban:
    Duration: 5
    Message: <red>Você foi banido por 5 minutos, penalidade por sair durante a luta.
    Broadcast-Enabled: true
    Broadcast-Message: <green>Covardes não serao tolerados nesse servidor.
  Unban:
    Message-Enabled: true
    Message: <darkaqua>Você saiu durante a luta, e como penalidade perdeu seus itens.
    Run-Commands:
    - say <player> logou depois de ter sido banido
  CombatLog:
    NPC:
      Enabled: false
      Despawn-Delay: 120
      Default-Aggressive: false
    Drop:
      Items: true
      Armor: true
      Exp: true
  Command:
    Disallow-All: false
    Freeze-Duration: 7
    Freeze-Message: <red>Não há como fugir de uma batalha!
    Disallowed-List:
    - tp
    - warp
    - home
    - tpa
    - creative
    - spawn
