#   ____ _ _      _   __        __
#  / ___| (_) ___| | _\ \      / /_ _ _ __ _ __
# | |   | | |/ __| |/ /\ \ /\ / / _` | '__| '_ \
# | |___| | | (__|   <  \ V  V / (_| | |  | |_) |
#  \____|_|_|\___|_|\_\  \_/\_/ \__,_|_|  | .__/
#                                         |_|
# Plugin by comniemeer
# Version 1.3.4
# Main configuration File

# Possible languages: en (English), de (Deutsch), fr (French), pt (Portuguese) or cz (Czech)
# Or add your own language file to the "Languages" folder and type here the name of the file.
Language: en

# Define here the default item for /invwarp
# Attention! If you use an item with an additional meta, like blue wool (35:11),
# you have to make that item in '' (example: DefaultWarpItem: '35:11')!
DefaultWarpItem: 2

# If you wish to use an item that opens the "/invwarp" menu, enable it here and define an item.
# Only players with the permission "clickwarp.invwarp.item" can use this function.
EnableInvwarpItem: true
InvwarpItem: 347

Sign:
  # Here you can edit the text that is replaced on a sign, if you write [Warp] in the first line.
  FirstLine: '&7[&6Warp&7]'

Delay:
  Warp:
    # Should a warp delay be activated?
    # Regardless, players with the permission "clickwarp.warp.instant" can warp immediately.
    EnableDelay: false

    # If true, the delay (seconds) can be specified here:
    Delay: 10

    # Shouldn't players move before teleport?
    EnableDontMove: true
    
    Sign:
      # Should there also be a delay when using warp-signs?
      Enable: true

  Teleport:
    # Should a teleport delay be activated?
    # Regardless, players with the permission "clickwarp.teleport.instant" can teleport immediately.
    EnableDelay: false

    # If true, the delay (seconds) can be specified here:
    Delay: 10

    # Shouldn't players move before teleport?
    EnableDontMove: true

# Edit the names of the inventorys here
Inventory:
  Warp: '&2&lWarps'
  Teleport: '&4&lTeleport'

# For this function you need Vault enabled on your server
# Download it at http://dev.bukkit.org/server-mods/vault/
Economy:
  # After setting this to "true", you have to reload/restart your server!
  Enable: false
  
  # Should the price be shown in /invwarp (last line)?
  ShowPrice: true
  
  # Edit here the format of the price:
  PriceFormat: '&7&oPrice: &6&o{price} {currency}'
  
  CurrencySingular: 'Dollar'
  CurrencyPlural: 'Dollars'
  
# End of the config #