#--------------------------------------------------------------------#
#                   ClearLag Configuration File                      #
#--------------------------------------------------------------------#
# Configure to your liking, reload the config by tying: /lagg reload #
#                                -                                   #
#        Here is a helpful tutorial on this configuration setup!     #
#   http://dev.bukkit.org/server-mods/clearlagg/pages/config-setup/  #
#--------------------------------------------------------------------#
#                     All possible mob names                         #
# http://dev.bukkit.org/server-mods/clearlagg/pages/mob-types/nodes/ #
#--------------------------------------------------------------------#
settings:
  auto-update: true
  enable-signs: true
  config-version: two
  broadcast-message: '&6[&b!&6] &6Foram Removidos +RemoveAmount Do Chão!'
  enable-scheduler: true
  enable-limit: true
  autoremoval-interval: 400
     
warning:
  autoremoval-warning: true
  autoremoval-warningdelay: 60
  broadcast-warning: true
  autoremoval-warningmessage: '&6[&b!&6] &6Removendo Itens do Chão em 1 Minuto'
     
remove:
  world-filter:
    - this_world
  broadcast-removal: true
  boat: true
  falling-block: true
  experienceOrb: true
  painting: true
  projectile: true
  item: true
  itemframe: false
  minecart: true
  primed-tnt: true
  arrow: true
  snowball: true
  fireball: true
  ender-signal: true
  mobs:
    - None
    - None
     
command-remove:
  world-filter:
    - this_world
  broadcast-removal: false
  boat: true
  falling-block: true
  experienceOrb: true
  painting: true
  projectile: true
  item: true
  itemframe: false
  minecart: false
  primed-tnt: true
  arrow: true
  snowball: true
  fireball: true
  ender-signal: true
  mobs:
    - Zombie
    - Creeper
     
check:
  world-filter:
    - this_world
  boat: true
  falling-block: true
  experienceOrb: true
  painting: true
  projectile: true
  item: true
  itemframe: false
  minecart: true
  primed-tnt: true
  arrow: true
  snowball: true
  fireball: true
  ender-signal: true
  mobs:
    creature: true
    animals: true
    monster: true
     
limit:
  max: 1000
  check-interval: 60
  world-filter:
    - this_world
  broadcast-removal: true
  remove:
  boat: true
  falling-block: true
  experienceOrb: true
  painting: true
  projectile: true
  item: true
  itemframe: false
  minecart: true
  primed-tnt: true
  arrow: true
  snowball: true
  fireball: true
  ender-signal: true
     
#This is /lagg killmobs, put what you DON'T want removed! 
kill-mobs:
   mob-filter:
        - Villager
        - Wolf