configuration:
  debug-mode: false
  language: english
misc:
  wand-item: 294
  check-time-every: 20
  teleport-on-reset: true
updater:
  channel: db
  remind-on-login: true
  permission-node: minereset.admin
