bypass-blocks: []
unprotectable-blocks: []
unbreakable-blocks: []
hiding-mask-blocks:
- '1'
- '2'
- '3'
- '4'
- '5'
- '7'
- '12'
- '13'
- '17'
- '18'
- '20'
- '24'
- '35'
- '43'
- '45'
- '47'
- '48'
- '49'
- '53'
- '60'
- '67'
- '80'
- '81'
- '82'
- '87'
- '88'
- '89'
- '99'
- '100'
- '108'
- '109'
- '110'
- '123'
- '124'
- '125'
- '128'
- '134'
- '135'
- '136'
tool-items:
- 256
- 257
- 258
- 269
- 270
- 271
- 273
- 274
- 275
- 277
- 278
- 279
- 284
- 285
- 286
- 290
- 291
- 292
- 293
- 294
repairable-items:
- 256
- 257
- 258
- 259
- 261
- 267
- 268
- 269
- 270
- 271
- 272
- 273
- 274
- 275
- 276
- 277
- 278
- 279
- 283
- 284
- 285
- 286
- 290
- 291
- 292
- 293
- 294
- 298
- 299
- 300
- 301
- 302
- 303
- 304
- 305
- 306
- 307
- 308
- 309
- 310
- 311
- 312
- 313
- 314
- 315
- 316
- 317
- 359
force-field-blocks:
- title: City Protection
  block: 19
  radius: 8
  custom-height: 15
  prevent-fire: true
  prevent-place: true
  prevent-destroy: true
  prevent-vehicle-destroy: true
  prevent-enderman-destroy: true
  prevent-explosions: true
  prevent-unprotectable: true
  prevent-item-frame-take: true
  prevent-flow: true
  protect-crops: true
  protect-inventories: true
  prevent-place-blacklist:
  - 153
  ?welcome-message: true
  ?farewell-message: true
  ?prevent-portal-enter: true
  ?prevent-portal-destination: true
  ?prevent-portal-create: true
  ?prevent-vehicle-enter: true
  ?prevent-vehicle-exit: true
  ?prevent-teleport: true
  command-blacklisting: true
  can-change-owner: true
  enable-on-src: true
  mixing-group: 1
  hidable: true
  cuboid: true
  mask-on-disabled: 80
- title: City Plot
  block: 0
  radius: 0
  custom-height: 15
  allowed-only-inside:
  - City Protection
  plot: true
  no-conflict: true
  prevent-fire: true
  prevent-place: true
  prevent-destroy: true
  prevent-vehicle-destroy: true
  prevent-enderman-destroy: true
  prevent-explosions: true
  prevent-unprotectable: true
  protect-inventories: true
  prevent-flow: true
  ?prevent-teleport: true
  protect-crops: true
  ?welcome-message: true
  ?farewell-message: true
  can-change-owner: true
  enable-on-src: true
  mixing-group: 1
  hidable: true
  cuboid: true
  mask-on-disabled: 80
- title: Entry Bouncer
  block: 0
  radius: 0
  prevent-entry: true
  prevent-unprotectable: true
  prevent-flow: true
  enable-on-src: true
  can-change-owner: true
  hidable: true
  cuboid: true
  mask-on-disabled: 80
- title: Grief Revert
  block: 0
  radius: 0
  custom-height: 15
  allow-grief:
  - 37
  - 38
  - 39
  - 40
  grief-revert: false
  grief-revert-safety: true
  ?welcome-message: true
  ?farewell-message: true
  enable-on-src: true
  can-change-owner: true
  hidable: true
  mixing-group: 1
  cuboid: true
  mask-on-disabled: 80
- title: Peace Keeper
  block: 19
  radius: 10
  prevent-pvp: true
  no-player-place: true
  prevent-mob-damage: true
  protect-animals: true
  protect-mobs: true
  protect-villagers: true
  hidable: true
  cuboid: true
  mask-on-disabled: 80
- title: Jack-o-Death
  block: 0
  radius: 0
  damage: 0
  no-conflict: true
  sneaking-bypass: true
  no-player-place: true
  mixing-group: 2
  mask-on-disabled: 80
- title: Creature Repeller
  block: 0
  radius: 0
  single-use: true
  prevent-mob-damage: true
  prevent-mob-spawn: true
  prevent-animal-spawn: true
  remove-mob: true
  no-conflict: true
  mixing-group: 1
  hidable: true
  cuboid: true
  mask-on-disabled: 80
- title: Air of Atlantis
  block: 0
  radius: 0
  custom-height: 256
  air: true
  no-conflict: true
  mixing-group: 1
  hidable: true
  cuboid: true
  mask-on-disabled: 80
- title: Proximity Snitch
  block: 0
  radius: 0
  snitch: true
  entry-alert: true
  no-conflict: true
  hidable: true
  mixing-group: 2
  cuboid: true
  mask-on-disabled: 80
- title: The Shocker
  block: 0
  radius: 0
  custom-height: 3
  lightning: true
  lightning-replace-block: 0
  sneaking-bypass: true
  breakable: true
  no-conflict: true
  mixing-group: 2
  mask-on-disabled: 80
- title: Proximity Mine
  block: 0
  radius: 0
  custom-height: 5
  mine: 5
  mine-has-fire: false
  mine-delay-seconds: 0
  breakable: true
  sneaking-bypass: true
  mixing-group: 2
  no-conflict: true
  mask-on-disabled: 80
- title: Launch Pad
  block: 0
  radius: 0
  launch: false
  no-conflict: true
  sneaking-bypass: true
  custom-volume: 20
  mixing-group: 2
  cuboid: true
  mask-on-disabled: 80
- title: Sky Cannon
  block: 0
  radius: 0
  custom-height: 3
  custom-volume: 20
  sneaking-bypass: true
  cannon: true
  no-conflict: true
  mixing-group: 2
  cuboid: true
  enable-with-redstone: true
  mask-on-disabled: 80
- title: Translocator
  block: 0
  radius: 0
  custom-volume: 5000
  enable-with-redstone: true
  translocation: true
  dynmap-area: true
  dynmap-disabled: true
  hidable: true
  translocation-blacklist:
  - 57
  - 41
  cuboid: true
  mask-on-disabled: 17
- title: GodStone
  block: 0
  radius: 0
  heal: 4
  feed: 2
  repair: 25
  neutralize-potions:
  - HARM
  - CONFUSION
  - BLINDNESS
  - HUNGER
  - WEAKNESS
  - POISON
  - SLOW
  no-conflict: true
  mixing-group: 2
  cuboid: true
  mask-on-disabled: 80
- title: Miner's Haste
  block: 0
  radius: 0
  custom-height: 128
  cuboid: true
  dynmap-area: true
  ^potions:
  - FAST_DIGGING
  - SPEED
  - JUMP
  potion-intensity:
  - 5
  - 3
  - 5
  enable-with-redstone: true
  no-fall-damage: true
  mask-on-disabled: 17
- title: Mild Forester
  block: 0
  radius: 0
  custom-height: 15
  forester: false
  ground-block: 2
  fertile-blocks:
  - 3
  - 2
  - 13
  - 87
  - 80
  - 88
  tree-types:
  - 0
  - 0
  - 0
  - 1
  - 1
  - 4
  shrub-types:
  - 1
  - 1
  - 1
  - 2
  - 2
  - 3
  - 4
  shrub-density: 64
  tree-count: 32
  grow-time: 10
  no-owner: true
  no-conflict: false
- title: Redwood Forester
  block: 0
  radius: 0
  custom-height: 15
  forester: false
  ground-block: 2
  fertile-blocks:
  - 3
  - 2
  - 13
  - 87
  - 80
  - 88
  tree-types:
  - 2
  - 2
  - 2
  - 3
  shrub-types:
  - 1
  shrub-density: 64
  tree-count: 32
  grow-time: 10
  no-owner: true
  no-conflict: false
- title: Jungle Forester
  block: 0
  radius: 0
  custom-height: 15
  forester: false
  ground-block: 2
  fertile-blocks:
  - 3
  - 2
  - 13
  - 87
  - 80
  - 88
  tree-types:
  - 0
  - 0
  - 7
  - 7
  - 7
  - 8
  - 8
  - 8
  - 8
  shrub-types:
  - 2
  shrub-density: 30
  tree-count: 64
  grow-time: 10
  no-owner: true
  no-conflict: false
- title: Birch Forester
  block: '18:7'
  radius: 20
  custom-height: 15
  forester: false
  ground-block: 2
  fertile-blocks:
  - 3
  - 2
  - 13
  - 87
  - 80
  - 88
  tree-types:
  - 4
  - 4
  - 8
  - 8
  - 7
  shrub-types:
  - 2
  shrub-density: 85
  tree-count: 64
  grow-time: 10
  no-owner: true
  no-conflict: false
log:
  translocation: true
  rollback: true
  fire: true
  entry: true
  place: true
  use: true
  pvp: true
  destroy: true
  destroy-area: false
  place-area: false
  unprotectable: true
  bypass-pvp: true
  bypass-delete: true
  bypass-place: true
  bypass-destroy: true
  conflict-place: true
  rents-and-purchases: true
notify:
  translocation: true
  rollback: true
  place: true
  destroy: true
  bypass-unprotectable: true
  bypass-pvp: true
  bypass-place: true
  bypass-destroy: true
  fly-zones: true
warn:
  instant-heal: true
  slow-heal: true
  slow-damage: true
  slow-feeding: true
  slow-repair: true
  fast-damage: true
  air: true
  fire: true
  entry: true
  place: true
  use: true
  pvp: true
  destroy: true
  destroy-area: true
  unprotectable: true
  launch: true
  cannon: true
  mine: true
settings:
  disable-messages: false
  prevent-removal-if-player-in-field: true
  disable-simpleclans-hook: false
  max-size-translocation: 100000
  max-size-translocation-for-redstone: 1000
  version: 12
  prevent-place-everywhere:
  - creative_world
  prevent-destroy-everywhere:
  - creative_world
  show-default-welcome-farewell-messages: true
  sneak-to-place-field: false
  sneak-to-place-normal-block: true
  disable-ground-info: false
  global-field-limit: 1000000
  no-refund-for-fields: false
  public-block-details: false
  drop-on-delete: true
  disable-alerts-for-admins: true
  disable-bypass-alerts-for-admins: false
  off-by-default: false
  lines-per-page: 12
  log-to-hawkeye: false
  show-debug-info: false
  blacklisted-worlds:
  - creative_world
  auto-allow-clan-on-fields: true
  check-once-per-block-on-move: false
  use-blockids-in-snitches: false
  fence-max-depth: 50
cuboid:
  defining-blocktype: 49
  visualization-blocktype: 20
cleanup:
  player-inactivity-purge-days: 180
  purge-banned-players: true
saving:
  frequency-seconds: 1
  max-records-per-snitch: 50
visualization:
  frame-block-type: 20
  block-type: 20
  seconds: 30
  new-dotted-style: true
  end-on-player-move: false
  mark-block-type: 49
  default-density: 8
  blocks-to-send: 100
  max-fields-to-visualize-at-once: 5
  ticks-between-sends: 10
grief-revert:
  min-interval-secs: 30
  black-list:
  - '92'
mysql:
  enable: false
  host: localhost
  port: 3306
  database: minecraft
  username: ''
  password: ''
