animationApiThreads: 4
bungee: 
  ipOnJoin: \\-
  uuidOnJoin: \\-
  forceEnable: \\-
  playerCount: 100
  playerList: -1
  servers: 1000000
  currentServerName: 1000000
  uuidAll: -1
  serverIP: -1
#Debug mode, if disabled, then some of the stack traces won't be visible in console.
debug: \\-
#Servers default language.
defaultLang: en
disableWeatherChange: \\-
earlyJoinKickMsg: Â§eStarting server...
earlyJoinProtection: 30
#EconomyAPI settings
economy: 
  balanceTypes: 
    default: 
      defaultValue: 100
      name: default
      suffix: $
#Migrate all the Economy data through Vault from an other Economy plugin, i.e. Essentials.
  migrate: \\-
#The type of SpigotLibs vault hook, available options:
#NONE - do NOT hook to Vault at all (not suggested)
#USER - hook to Vault as an Economy user (suggested if you don't want to use SpigotLibs Economy management)
#PROVIDER - hook to Vault as an Economy provider (override other Economy plugins, like Essentials)
  vaultHookType: USER
#Hook to the clips PlaceholderAPI in order to obtain more variables.
phaHook: +
playerEval: \\-
allowAllPermsForAuthor: +
#PlayerFile settings
playerFile: 
  backend: FILE
  file: players.yml
  mysql: 
    table: PlayerData
    database: SpigotLib
    host: 127.0.0.1
    password: root
    timeout: 10000
    username: root
#Allows sync and async metrics of the truth server tps, for the <tps>
#variable, it also helps to detect informations about possible server crashes.
tpsMeter: 
  checkTime: 10000
  limit: 15